# Generated by Django 4.2.7 on 2026-01-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='Numpy array representation of the face encoding', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_faces/'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_absence_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
