# Generated by Django 5.2.11 on 2026-02-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_face_encoding_student_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='filiere',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='matiere',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='prenom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
