# Generated by Django 5.2.11 on 2026-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_professor_full_name_professor_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='role',
            field=models.CharField(default='professor', max_length=50),
        ),
    ]
