# Generated by Django 5.2.11 on 2026-03-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_adminaccount_remove_professor_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
