# Generated by Django 4.2.7 on 2026-01-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('model_used', models.CharField(choices=[('haar', 'Haar Cascade'), ('hog', 'HOG'), ('cnn', 'CNN'), ('facenet', 'FaceNet')], max_length=50)),
                ('embedding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='accounts.student')),
            ],
            options={
                'db_table': 'student_faces',
            },
        ),
    ]
