# Generated by Django 4.2.7 on 2026-01-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='duration',
            field=models.FloatField(default=1.5, help_text='Duration in hours'),
        ),
    ]
