# Generated by Django 4.2.7 on 2026-02-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
