# Generated by Django 5.2.11 on 2026-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesession_seance_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencelevelrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
